### ISSUE TITLE
What is autoexposure ?

### ISSUE THREAD

**Issue by yjhong89** [Kai-46/nerfplusplus#31]
Hi, I am YJHong and thanks for your great work!

I wonder what is autoexposure option for nerf.

Is it necessary option to run nerf++ code?

Thank you,
YJHong.

**Comment by Kai-46** [comment]
Auto-exposure is one of the camera settings during image capture. This option is not necessary to run this repo. 

But note that, ideally, to capture photos for view synthesis tasks, one should turn off the auto-exposure (as well as auto white balance) in a camera. But unfortunately, the tanks and temples data seem to be captured with auto-exposure turned on. That's why this code implements the auto-exposure functionality trying to account for that (but I did not fully test it).

**Comment by yjhong89** [comment]
@Kai-46 
Thanks!
